# Generated by Django 3.2.4 on 2021-09-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://images.freeimages.com/images/large-previews/825/linked-hands-1308777.jpg', max_length=500),
        ),
    ]
